routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
    //return view('welcome');
    //return view('connect.login');
//});
Route::get('/', 'ConnectController@index')->name('login');
/** */

/**Ruta principal */
//Route::get('dashboard','Admin\AdminController@index')->name('admin')->middleware(['auth','Isadmin']);
/**ROUTE FOR ADMIM */
Route::get('dashboard', [AdminController::class, 'index'])->name('admin')->middleware(['auth','Isadmin']);
Route::get('/get-data-sales', [AdminController::class, 'get_sales'])->name('get-data-sales')->middleware(['auth','Isadmin']);
/**ROUTE FOR USER */
Route::get('userdashboard', [UserdashboardController::class, 'index'])->name('userdashboard')->middleware('auth');
Auth::routes();

/**RUTAS DE AUTENTICACION DEL LOGIN*/
Route::get('/login', 'ConnectController@index')->name('login');
Route::post('/login','ConnectController@postLogin')->name('login');
/**RUTA DE CERRAR CESION */
Route::get('/logout', 'ConnectController@getLogout')->name('logout')->middleware('auth');


//Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

/**RUTAS DEL USUARIO PRINCIPAL*/
Route::resource('admin/role', 'RoleController')->names('role')->middleware('auth');
Route::resource('admin/user', 'UserController')->names('user')->middleware('auth');
Route::post('newuser', 'UserController@postRegister')->name('register')->middleware('auth');
Route::post('updatepasssword', 'UserController@updatepassword')->name('updatepasssword')->middleware('auth');
Route::get('delete-users/{id}', 'UserController@delete_user')->name('delete-users')->middleware('auth');
//Route::post('savedevolucionproduct', 'Devolucion\DevolucionventaController@store')->name('savedevolucionproduct');

/**RUTAS DE CATEGORIA */
Route::get('almacen/categoria', 'Categoria\CategoriaController@index')->name('categoria')->middleware('auth');
Route::post('/savecategoria', 'Categoria\CategoriaController@store')->name('savecategoria')->middleware('auth');
Route::get('showcategoria', 'Categoria\CategoriaController@show')->name('showcategoria')->middleware('auth');
Route::get('deletecategoria/{id}', 'Categoria\CategoriaController@destroy')->name('deletecategoria')->middleware('auth');
Route::get('categoria-list/{id}', 'Categoria\CategoriaController@edit')->name('categoria-list')->middleware('auth');
Route::post('categoriaupdate', 'Categoria\CategoriaController@update')->name('categoriaupdate')->middleware('auth');
//Route::get('product-list', 'Categoria\CategoriaController@show');

/**RUTAS PARA EL ARTICULO*/ 
Route::get('almacen/articulo', 'Articulo\ArticuloController@index')->name('articulo')->middleware('auth');
Route::post('savearticulo', 'Articulo\ArticuloController@store')->name('savearticulo')->middleware('auth');
Route::get('showproducto', 'Articulo\ArticuloController@show')->name('showproducto')->middleware('auth');
Route::get('product-list/{id}', 'Articulo\ArticuloController@edit')->name('product-list')->middleware('auth');
Route::post('updateproduct', 'Articulo\ArticuloController@update')->name('updateproduct')->middleware('auth');
Route::get('delete-category/{id}', 'Articulo\ArticuloController@destroy')->name('delete-category')->middleware('auth');

/**RUTAS PARA EL PROVEEDOR*/
Route::get('compras/proveedor', 'Proveedor\ProveedorController@index')->name('proveedor')->middleware('auth');
Route::post('saveproveedor', 'Proveedor\ProveedorController@store')->name('saveproveedor')->middleware('auth');
Route::get('showproveedor', 'Proveedor\ProveedorController@show')->name('showproveedor')->middleware('auth');
Route::get('provider-list/{id}', 'Proveedor\ProveedorController@edit')->name('provider-list')->middleware('auth');
Route::post('updateprovider', 'Proveedor\ProveedorController@update')->name('updateprovider')->middleware('auth');
Route::get('delete-provider/{id}', 'Proveedor\ProveedorController@destroy')->name('delete-provider')->middleware('auth');
/**RUTAS DE LOS INGRESOS COMPRAS DE LOS PRODUCTOS */
Route::resource('compras/entradas', 'Ingreso\IngresoController')->names('entradas')->middleware('auth');
Route::get('nombrearticuloentrada', 'Ingreso\IngresoController@find_nombre')->name('nombrearticuloentrada')->middleware('auth');
Route::post('temp_datos', 'Ingreso\IngresoController@save_temp')->name('temp_datos')->middleware('auth');
Route::post('showproveedores', 'Ingreso\IngresoController@searh_proveedores')->name('showproveedores')->middleware('auth');
// Route::post('', 'Ingreso\IngresoController@')->name('deleteproduct');
Route::post('deleteproduct', 'Ingreso\IngresoController@delete_prod')->name('deleteproduct')->middleware('auth');
Route::post('showproductostemp', 'Ingreso\IngresoController@show_prod')->name('showproductostemp')->middleware('auth');
Route::post('saveproductoentrada', 'Ingreso\IngresoController@store')->name('saveproductoentrada')->middleware('auth');
Route::get('showlistentradas', 'Ingreso\IngresoController@show')->name('showlistentradas')->middleware('auth');

Route::get('get-entrada/{id}', 'Ingreso\IngresoController@get_products')->name('get-entrada')->middleware('auth');

// Route::get('registro', 'Ingreso\IngresoController@create')->name('entradasproductos');

/**RUTAS DE LOS CLIENTES*/
Route::get('ventas/cliente', 'Cliente\ClienteController@index')->name('cliente')->middleware('auth');
Route::post('/savecliente', 'Cliente\ClienteController@store')->name('savecliente')->middleware('auth');
Route::get('showlistcustomers', [ClienteController::class, 'show'])->name('showlistcustomers')->middleware('auth');
Route::get('/get-data-cliente/{id}',[ClienteController::class, 'get_cliente'])->name('get-data-cliente')->middleware('auth'); 
Route::post('/updatecliente', 'Cliente\ClienteController@update')->name('updatecliente')->middleware('auth');
Route::get('/down-cliente/{id}',[ClienteController::class, 'down_cliente'])->name('down-cliente')->middleware('auth'); 

/**RUTAS DEL MODULO DE VENTAS*/
Route::resource('ventas/venta', 'Venta\VentaController')->names('venta')->middleware('auth');
Route::post('findproducto', 'Venta\VentaController@find_product')->name('findproducto')->middleware('auth');
Route::post('saveprodtempvent', 'Venta\VentaController@save_product_temp')->name('saveprodventa')->middleware('auth');
Route::post('showproductosventatemp', 'Venta\VentaController@show_vent_prod_tmp')->name('showproductosventatemp')->middleware('auth');
Route::post('deleteventaproducto', 'Venta\VentaController@delete_venta_product')->name('deleteventaproduct')->middleware('auth');
Route::post('saveformventa', 'Venta\VentaController@store')->name('saveformventa')->middleware('auth');
Route::post('deleteventa', 'Venta\VentaController@delete_venta_general')->name('deleteventaproduct')->middleware('auth');
Route::get('showlistventas', 'Venta\VentaController@show')->name('showlistventas')->middleware('auth');
Route::get('venta-detalle/{id}', 'Venta\VentaController@show_edit')->name('venta-detalle')->middleware('auth');
//Route::get('ventas/venta', 'Venta\VentaController@index')->name('venta');

/**DEVOLUCIONES DE UNA VENTA*/
Route::resource('devoluciones/venta', 'Devolucion\DevolucionventaController')->names('devolucion')->middleware('auth');
Route::get('/products_devolucion/{folio}', 'Devolucion\DevolucionventaController@show_devolucion_venta')->name('products_devolucion')->middleware('auth');
Route::post('/savedevolucionproduct', 'Devolucion\DevolucionventaController@store')->name('savedevolucionproduct')->middleware('auth');

/**RUTAS DE CAJA INICIO*/
Route::get('caja/cajainicio', [CajainicioController::class, 'index'])->name('cajainicio')->middleware('auth');
Route::post('/saveapertura', [CajainicioController::class, 'store'])->name('saveapertura')->middleware('auth');
/**RUTAS DE CORTE DE CAJA*/
Route::get('caja/corte', [CortecajaController::class, 'index'])->name('corte')->middleware('auth');
Route::post('/savecortecaja', [CortecajaController::class, 'store'])->name('savecortecaja')->middleware('auth');
Route::get('showlistcortes', [CortecajaController::class, 'show'])->name('showlistcortes')->middleware('auth');

Route::get('caja/corteparcial', [CorteparcialController::class, 'index'])->name('corteparcial')->middleware('auth');
Route::get('showlistcajeros', [CorteparcialController::class, 'show'])->name('showlistcajeros')->middleware('auth');
Route::post('/saveformparcial', [CorteparcialController::class, 'store'])->name('saveformparcial')->middleware('auth');

/**TICKET FOR THE CUTTING OF THE CASHIER'S DAY*/
Route::get('/ticketcorte', [CortecajaController::class, 'ticket'])->name('ticketcorte')->middleware('auth');

/**REPORTS*/
Route::get('/graph', [GraphicsController::class, 'index'])->name('graph')->middleware('auth');
Route::post('/getdatagraph', [GraphicsController::class, 'get_data'])->name('getdatagraph')->middleware('auth');
Route::post('/getmesgraph', [GraphicsController::class, 'get_data_mes'])->name('getmesgraph')->middleware('auth');

/**ROUTE FOR SEND TICKET TO EMAIL*/
/*Route::get('/contactanos', function() {
 $correo = new SendticketMailable;
 Mail::to("rogercode01@gmail.com")->send($correo);
 return "Mensaje enviado";
});*/
/*ROUTE FOR SEND EMAIL */
Route::post('/contact', [TicketController::class, 'sendEmail'])->name('contact')->middleware('auth');

/**ROUTE FOR CONFIGURATION*/
Route::get('/config', [ConfiguracionController::class, 'index'])->name('config')->middleware('auth');
Route::post('/saveconf', [ConfiguracionController::class, 'update'])->name('saveconf')->middleware('auth');
/*Route::get('/contactanos', function() {
 $correo = new SendticketMailable;
 Mail::to("rogercode01@gmail.com")->send($correo);

resources/views/compras/ingreso/create.blade.php
@extends('layouts.admin')
@section('contenido')

<section>
  <ol class="breadcrumb" style="border:1px solid #CDC7C7;background:white;margin-bottom:1px;margin-top:3px;padding: 5px 0px 0px 6px !important;">
    <!--a href="#"><li class="breadcrumb-item btn btn-info btn-sm">Lista de entradas de productos</li></a-->
    <a href="{{url('compras/entradas')}}"><h5><span class="badge bg-secondary">Lista de entrada de productos</span></h5></a>
    <!--li class="breadcrumb-item"><a href="#">Menu 1</a></li>
    <li class="breadcrumb-item"><a href="#">Menu 2</a></li>
    <li class="breadcrumb-item"><a href="#">Menu 3</a></li-->
  </ol>
</section>
<!-- Main content -->
<section class="content margincss">
      <div class="row">
        <div class="col-md-9">
          <div class="card card-primary card-outline">
            <div class="card-header">
                <!--FORMULARIO QUE GUARDA EL PRODUCTO TEMPORALMENTE-->
                {!! Form::open(['id'=>'temp_datos_entradas'])!!}
                    <div class="row">
                        <!--Input que tiene el id del usuario identificado-->
                        <input type="text" size="4"  id="id_user" name="id_user" value="{{Auth::user()->id}}" hidden="true">
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span style="background:white;" class="input-group-text" id="basic-addon1"><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </div>
                                    <input id="IngresoNombreArticulo" type="text" class="form-control" placeholder="Nombre">
                                    <!--Input que tiene el id del articulo-->
                                    <input type="text" name="idarticulo" id="idarticulo" size="4" hidden="true">
                                    <!---->
                                    <!--Input que tiene el codigo del articulo-->
                                    <input type="text" name="IngresoCodigoArticulo" id="IngresoCodigoArticulo" size="4" hidden="true">
                                    <!---->
                                    <!--Input que tiene el nombre del articulo-->
                                    <input type="text" id="pnombrearticulo" name="pnombrearticulo" size="4" hidden="true"> 
                                    <!--Input-->
                                </div>
                            </div>                        
                        </div>
                    </div>
                    <!--fin del row codigo y nombre-->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Cantidad</label>
                                <input type="number" step="any" class="form-control" id="pcantidad" name="pcantidad" min="0" placeholder="0.00" onkeypress="return filterFloat(event,this);">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">P. compra</label>
                                <input type="number" step="any" class="form-control" id="pprecio_compra" name="pprecio_compra" min="0" placeholder="0.00" onkeypress="return filterFloatdecimal2(event,this);">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">P. venta</label>
                                <input type="number" step="any" class="form-control" id="pprecio_venta" name="pprecio_venta" min="0" placeholder="0.00" onkeypress="return filterFloatdecimal2(event,this);">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group btn_css">
                                <button type="submit" id="btn_addentradas" class="btn btn-outline-primary">Agregar</button>
                            </div>
                        </div>
                    </div>
                    @include('custom.validate_save_form_ajax')
                {!!Form::close()!!}    
            </div>
            <!--FORMULARIO QUE GUARDA LA ENTRADA DE LOS PRODUCTOS-->
            {!!Form::open(['id'=>'save_producto_entradas'])!!}
            <div class="card-body">
                <!-- <h5 class="card-title">Special title treatment</h5> -->
                <Input type="text" name="user_id" hidden="true" value="{{Auth::user()->id}}" id="user_id"> 
                <div class="table-responsive-sm tableFixHead">
                    <table id="detalles" style="width: 100%;" class="table table-sm table-bordered table-hover text-center">
                        <thead>
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">Codigo</th>
                            <th scope="col">Articulo</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Precio compra</th>
                            <th scope="col">Precio venta</th>
                            <th scope="col">Subtotal</th>
                            <th scope="col"><i class="fas fa-trash-alt"></i></th>
                            </tr>
                        </thead>
                        <tbody id="tabla_tmp_productos">

                        </tbody>     
                    </table>
                </div>
                <!--terminacion del div del scroll de la tabla-->
                <div class="container" style="border:1px solid #A9A9A9;">
                    <div class="row">
                        <div class="col-md-10 text-right">
                            <h5 class="input_all_total"><strong>Total $</strong></h5>
                        </div>
                        <div class="col-md-2">
                            <input type="text" name="total_general" id="total_general" class="form-control" placeholder="00.00" readonly>
                        </div>
                    </div>
                </div>
            </div>
          </div> 
        </div>
        <!-- /.col -->
        <div class="col-md-3">
            <!--a href="#" class="btn btn-primary btn-block mb-3">Entrada de productos</a>-->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Datos</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body p-0">
                    <ul class="nav nav-pills flex-column">
                        <li class="nav-item">
                            <!-- Actual search box -->
                            <div class="form-group">
                                <label for="">Buscar el proveedor</label>
                                <div class="autocomplete" style="width:300px;">
                                    <input id="myInput" type="text" placeholder="Escribir para empezar buscar" class="form-control" autocomplete="off">
                                </div>
                                <ul id="autocompleteli" tabindex='1' class="list-group"></ul>
                                <input type="text" name="idproveedor" id="idproveedor" autocomplete="off" hidden="true">
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="form-group">
                                <label for="">Folio</label>
                                <input type="text" class="form-control" value="{{$folio}}" name="folio" id="folio" readonly>
                            </div>
                        </li>
                        <li class="nav-item">
                            <label for="">Total $</label>
                            <input type="text" class="form-control" name="total_input" id="total_input" placeholder="00.00" readonly>
                        </li>
                        <li class="nav-item"><br>
                            <div class="form-group">
                                <button type="submit" id="form_save_entradas" class="btn btn-secondary btn-block">Aceptar</button>
                            </div>
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
                <!-- /.card-body -->
            </div> 
            {!!Form::close()!!} 
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
<!-- /.content -->

<!-- STYLE OF MY VIEW -->
<style>
.btn_css{
    margin-top: 32px;
}
/*****************************************************************/
/*the container must be positioned relative:*/
#autocompleteli{
     position: absolute;
  border: 1px solid #d4d4d4;
  border-bottom: none;
  border-top: none;
  z-index: 99;
  background:red;
  /*position the autocomplete items to be the same width as the container:*/
  /*top: 100%;
  /*left: 0;
  right: 0;*/
}
#autocompleteli li{
  padding: 10px;
  cursor: pointer;
  border-bottom: 1px solid #d4d4d4;
  width: 100%;
}
.selected {
    color: white;
    background: #7f8c8d;
}
</style>
@push('ScriptEntradaProductos')
<script src="{{asset('js/funciones_entradas/entradas.js')}}" type="module"></script> 
@endpush
@endsection

resources/views/compras/ingreso/header.blade.php
<section class="content margindivsection">
    <div class="d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
      <div class="d-flex align-items-center">
        <div>
          <a href="{{route('entradas.create')}}" class="btn btn-secondary btn-sm mr-3" id="showmodalsaveproduct">
            <i class="fa fa-archive"></i>
            <strong> Nueva entrada de productos</strong>
          </a>
        </div>
        <!--div>
          <button type="button" class="btn btn-info btn-sm mr-3">
            <i class="fa fa-archive"></i>
            <strong>Agregar nueva categoria</strong>
          </button>
        </div>
        <div>
          <button type="button" class="btn btn-info btn-sm mr-3">
            <i class="fa fa-archive"></i>
            <strong>Agregar nueva categoria</strong>
          </button>
        </div-->
      </div>
    </div>
</section>

resources/views/compras/ingreso/index.blade.php
@extends('layouts.admin')
@section('contenido')
@include('compras.ingreso.header')
<section class="content margindivsection">    
    <div class="card">
        <!-- /.card-header -->
        <div class="card-body">
            <div class="table-responsive">
                <table id="entradas_tabla" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Fecha</th>
                            <th>Proveedor</th>
                            <th>Folio</th>
                            <th>Total</th>
                            <th>Estado</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>        
                </table>
            </div>
        </div><!-- /.card-body -->
    </div>
</section>          
<!--MODAL THAT SHOW PRODUCTS THAT ENTER-->
<div class="modal fade" id="Modalentradasproductos" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Entradas de productos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
            <div class="row">
                <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">
                    <div class="form-group">
                        <label for="cliente">Proveedor</label>
                        <p id="proveedor_entrada"></p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">
                    <div class="form-group">
                        <label for="tipo">Fecha</label>
                        <p id="fecha_entrada"></p>
                    </div>
                </div> 
                <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">
                    <div class="form-group">
                        <label for="folio">Folio</label>
                        <p id="folio_entrada"></p>
                    </div>
                </div>  
            </div><!--fin del primer row-->
            <div id="" class="">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        <div class="row">
                            <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <table id="detalles" class="table table-sm table-bordered text-center">
                                    <thead>
                                        <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Cantidad</th>
                                        <th scope="col">Articulo</th>
                                        <th scope="col">Precio compra</th>
                                        <th>Subtotal</th>
                                        </tr>
                                    </thead>
                                    <tbody id="show_details_entradas">
                                    
                                    </tbody>
                                </table>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="row">
                                        <div class="col">
                                        </div>
                                        <div class="col-md-2 text-center" >
                                            <h6 style="margin-top:5px;"><strong> Total : </strong></h6>
                                        </div>
                                        <div class="col col-md-2 text-center">
                                            $ <input type="text" name="" id="total_entrada" class="size_input lectura" value="200.00" readonly>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>   
                    </div>
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div><!--FIn del modal-->
<!--templates for javasacript that show list of products-->
<template id="template-prod">
    <tr>
        <td class="prod-consecutivo">${i}</td>
        <td class="prod-cantidad"><input type="text" name="" class="size_input_change lectura" value=`${item.cantidad}` onkeypress="return filterFloat(event,this);"></td>
        <td class="prod-nombre">${item.nombre}</td>
        <td class="prod-precio_compra"><input type="text" name="" class="size_input lectura" value=`${item.precio_compra}` readonly></td>
        <td class="prod-subtotal"><input type="text" name="" class="size_input lectura" value=`${item.subtotal}` readonly></td>
    </tr>
</template>
<!--STYLE MY VIEW-->
<style>
.head_css{
    margin-top: 10px;
}

</style>
@push('ScriptEntradasIndex')
<script src="{{asset('js/funciones_entradas/entradas_index.js')}}"></script> 
@endpush
@endsection