routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\User;
use App\Permission\Models\Role;
use App\Permission\Models\Permission;
//use Illuminate\Support\Facades\Gate;
/**use controller version 8 */
use App\Http\Controllers\Caja\CajainicioController;
use App\Http\Controllers\Caja\CortecajaController;
use App\Http\Controllers\Caja\CorteparcialController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserdashboardController;
use App\Http\Controllers\Cliente\ClienteController;
use App\Http\Controllers\Reportes\GraphicsController;
use App\Http\Controllers\Configuracion\ConfiguracionController;
/**IMPORT DATA FROM EMAILS */
use App\Http\Controllers\Email\TicketController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
    //return view('welcome');
    //return view('connect.login');
//});
Route::get('/', 'ConnectController@index')->name('login');
/** */

/**Ruta principal */
//Route::get('dashboard','Admin\AdminController@index')->name('admin')->middleware(['auth','Isadmin']);
/**ROUTE FOR ADMIM */
Route::get('dashboard', [AdminController::class, 'index'])->name('admin')->middleware(['auth','Isadmin']);
Route::get('/get-data-sales', [AdminController::class, 'get_sales'])->name('get-data-sales')->middleware(['auth','Isadmin']);
/**ROUTE FOR USER */
Route::get('userdashboard', [UserdashboardController::class, 'index'])->name('userdashboard')->middleware('auth');
Auth::routes();

/**RUTAS DE AUTENTICACION DEL LOGIN*/
Route::get('/login', 'ConnectController@index')->name('login');
Route::post('/login','ConnectController@postLogin')->name('login');
/**RUTA DE CERRAR CESION */
Route::get('/logout', 'ConnectController@getLogout')->name('logout')->middleware('auth');


//Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

/**RUTAS DEL USUARIO PRINCIPAL*/
Route::resource('admin/role', 'RoleController')->names('role')->middleware('auth');
Route::resource('admin/user', 'UserController')->names('user')->middleware('auth');
Route::post('newuser', 'UserController@postRegister')->name('register')->middleware('auth');
Route::post('updatepasssword', 'UserController@updatepassword')->name('updatepasssword')->middleware('auth');
Route::get('delete-users/{id}', 'UserController@delete_user')->name('delete-users')->middleware('auth');
//Route::post('savedevolucionproduct', 'Devolucion\DevolucionventaController@store')->name('savedevolucionproduct');

/**RUTAS DE CATEGORIA */
Route::get('almacen/categoria', 'Categoria\CategoriaController@index')->name('categoria')->middleware('auth');
Route::post('/savecategoria', 'Categoria\CategoriaController@store')->name('savecategoria')->middleware('auth');
Route::get('showcategoria', 'Categoria\CategoriaController@show')->name('showcategoria')->middleware('auth');
Route::get('deletecategoria/{id}', 'Categoria\CategoriaController@destroy')->name('deletecategoria')->middleware('auth');
Route::get('categoria-list/{id}', 'Categoria\CategoriaController@edit')->name('categoria-list')->middleware('auth');
Route::post('categoriaupdate', 'Categoria\CategoriaController@update')->name('categoriaupdate')->middleware('auth');
//Route::get('product-list', 'Categoria\CategoriaController@show');

/**RUTAS PARA EL ARTICULO*/ 
Route::get('almacen/articulo', 'Articulo\ArticuloController@index')->name('articulo')->middleware('auth');
Route::post('savearticulo', 'Articulo\ArticuloController@store')->name('savearticulo')->middleware('auth');
Route::get('showproducto', 'Articulo\ArticuloController@show')->name('showproducto')->middleware('auth');
Route::get('product-list/{id}', 'Articulo\ArticuloController@edit')->name('product-list')->middleware('auth');
Route::post('updateproduct', 'Articulo\ArticuloController@update')->name('updateproduct')->middleware('auth');
Route::get('delete-category/{id}', 'Articulo\ArticuloController@destroy')->name('delete-category')->middleware('auth');

/**RUTAS PARA EL PROVEEDOR*/
Route::get('compras/proveedor', 'Proveedor\ProveedorController@index')->name('proveedor')->middleware('auth');
Route::post('saveproveedor', 'Proveedor\ProveedorController@store')->name('saveproveedor')->middleware('auth');
Route::get('showproveedor', 'Proveedor\ProveedorController@show')->name('showproveedor')->middleware('auth');
Route::get('provider-list/{id}', 'Proveedor\ProveedorController@edit')->name('provider-list')->middleware('auth');
Route::post('updateprovider', 'Proveedor\ProveedorController@update')->name('updateprovider')->middleware('auth');
Route::get('delete-provider/{id}', 'Proveedor\ProveedorController@destroy')->name('delete-provider')->middleware('auth');
/**RUTAS DE LOS INGRESOS COMPRAS DE LOS PRODUCTOS */
Route::resource('compras/entradas', 'Ingreso\IngresoController')->names('entradas')->middleware('auth');
Route::get('nombrearticuloentrada', 'Ingreso\IngresoController@find_nombre')->name('nombrearticuloentrada')->middleware('auth');
Route::post('temp_datos', 'Ingreso\IngresoController@save_temp')->name('temp_datos')->middleware('auth');
Route::post('showproveedores', 'Ingreso\IngresoController@searh_proveedores')->name('showproveedores')->middleware('auth');
// Route::post('', 'Ingreso\IngresoController@')->name('deleteproduct');
Route::post('deleteproduct', 'Ingreso\IngresoController@delete_prod')->name('deleteproduct')->middleware('auth');
Route::post('showproductostemp', 'Ingreso\IngresoController@show_prod')->name('showproductostemp')->middleware('auth');
Route::post('saveproductoentrada', 'Ingreso\IngresoController@store')->name('saveproductoentrada')->middleware('auth');
Route::get('showlistentradas', 'Ingreso\IngresoController@show')->name('showlistentradas')->middleware('auth');

Route::get('get-entrada/{id}', 'Ingreso\IngresoController@get_products')->name('get-entrada')->middleware('auth');

// Route::get('registro', 'Ingreso\IngresoController@create')->name('entradasproductos');

/**RUTAS DE LOS CLIENTES*/
Route::get('ventas/cliente', 'Cliente\ClienteController@index')->name('cliente')->middleware('auth');
Route::post('/savecliente', 'Cliente\ClienteController@store')->name('savecliente')->middleware('auth');
Route::get('showlistcustomers', [ClienteController::class, 'show'])->name('showlistcustomers')->middleware('auth');
Route::get('/get-data-cliente/{id}',[ClienteController::class, 'get_cliente'])->name('get-data-cliente')->middleware('auth'); 
Route::post('/updatecliente', 'Cliente\ClienteController@update')->name('updatecliente')->middleware('auth');
Route::get('/down-cliente/{id}',[ClienteController::class, 'down_cliente'])->name('down-cliente')->middleware('auth'); 

/**RUTAS DEL MODULO DE VENTAS*/
Route::resource('ventas/venta', 'Venta\VentaController')->names('venta')->middleware('auth');
Route::post('findproducto', 'Venta\VentaController@find_product')->name('findproducto')->middleware('auth');
Route::post('saveprodtempvent', 'Venta\VentaController@save_product_temp')->name('saveprodventa')->middleware('auth');
Route::post('showproductosventatemp', 'Venta\VentaController@show_vent_prod_tmp')->name('showproductosventatemp')->middleware('auth');
Route::post('deleteventaproducto', 'Venta\VentaController@delete_venta_product')->name('deleteventaproduct')->middleware('auth');
Route::post('saveformventa', 'Venta\VentaController@store')->name('saveformventa')->middleware('auth');
Route::post('deleteventa', 'Venta\VentaController@delete_venta_general')->name('deleteventaproduct')->middleware('auth');
Route::get('showlistventas', 'Venta\VentaController@show')->name('showlistventas')->middleware('auth');
Route::get('venta-detalle/{id}', 'Venta\VentaController@show_edit')->name('venta-detalle')->middleware('auth');
//Route::get('ventas/venta', 'Venta\VentaController@index')->name('venta');

/**DEVOLUCIONES DE UNA VENTA*/
Route::resource('devoluciones/venta', 'Devolucion\DevolucionventaController')->names('devolucion')->middleware('auth');
Route::get('/products_devolucion/{folio}', 'Devolucion\DevolucionventaController@show_devolucion_venta')->name('products_devolucion')->middleware('auth');
Route::post('/savedevolucionproduct', 'Devolucion\DevolucionventaController@store')->name('savedevolucionproduct')->middleware('auth');

/**RUTAS DE CAJA INICIO*/
Route::get('caja/cajainicio', [CajainicioController::class, 'index'])->name('cajainicio')->middleware('auth');
Route::post('/saveapertura', [CajainicioController::class, 'store'])->name('saveapertura')->middleware('auth');
/**RUTAS DE CORTE DE CAJA*/
Route::get('caja/corte', [CortecajaController::class, 'index'])->name('corte')->middleware('auth');
Route::post('/savecortecaja', [CortecajaController::class, 'store'])->name('savecortecaja')->middleware('auth');
Route::get('showlistcortes', [CortecajaController::class, 'show'])->name('showlistcortes')->middleware('auth');

Route::get('caja/corteparcial', [CorteparcialController::class, 'index'])->name('corteparcial')->middleware('auth');
Route::get('showlistcajeros', [CorteparcialController::class, 'show'])->name('showlistcajeros')->middleware('auth');
Route::post('/saveformparcial', [CorteparcialController::class, 'store'])->name('saveformparcial')->middleware('auth');

/**TICKET FOR THE CUTTING OF THE CASHIER'S DAY*/
Route::get('/ticketcorte', [CortecajaController::class, 'ticket'])->name('ticketcorte')->middleware('auth');

/**REPORTS*/
Route::get('/graph', [GraphicsController::class, 'index'])->name('graph')->middleware('auth');
Route::post('/getdatagraph', [GraphicsController::class, 'get_data'])->name('getdatagraph')->middleware('auth');
Route::post('/getmesgraph', [GraphicsController::class, 'get_data_mes'])->name('getmesgraph')->middleware('auth');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Permission\Traits\UserTrait;

class User extends Authenticatable
{
    use Notifiable,UserTrait ;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'estatus', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    //es: desde aqui
    //en: from here 
    /**function que se ejecuta desde el seeder*/
    // public function roles(){
    //     return $this->belongsToMany('App\Permission\Models\Role')->withTimesTamps();
    // }

    // public function havePermission($permission){
    //     //return $this->roles;
    //     foreach($this->roles as $role){
    //         if($role['full-access'] == "yes"){
    //             return 'true full access';
    //         }
    //         foreach ($role->permissions as $perm) {
    //             if($perm->slug == $permission){
    //                 return 'true por permisos';
    //             }
    //         }
    //     }
    //     return 'false';
    // }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

use App\Permission\Models\Role;
use App\User;
use Response,Validator, Hash;

class UserController extends Controller
{
    public function index()
    {
        Gate::authorize('haveaccess','admin_user.index');
        $users = User::with('roles')->where('estatus','=',1)->orderBy('id','Desc')->paginate(2);
        //return $users;
        return view('admin.user.index',compact('users'));
    }

    public function edit(User $user)
    {
        
        $roles = Role::orderBy('name')->get();
        // return $roles;
        return view('admin.user.edit',compact('roles','user'));
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'=>'required|max:50|unique:users,name,'.$user->id,
            'email'=>'required|max:50|unique:users,email,'.$user->id,
            
        ]);

        $rol = e($request->input('roles'));

        if ($rol === "selecciona") {

            return back()->with('status_success','Necesitas selecionar un rol para el usuario');
        }
        // dd($request->all());
        $user->update($request->all());
        // $user = new User;
        // $user->name = e($request->input('name'));
        // $user->email = e($request->input('email'));
        // $user->password = Hash::make($request->input('password'));
        
        $user->roles()->sync($request->get('roles'));

        return redirect()->route('user.index')->with('status_success', 'Datos actualizados correctamente');
    }

    public function show(User $user)
    {
        $roles = Role::orderBy('name')->get();
        // return $roles;
        return view('admin.user.view',compact('roles','user'));
    }

    /**por el momento esta function no se utiliza*/
   /*public function destroy(User $user)
    {
        $this->authorize('haveaccess','user.destroy');
        $user->delete();
        return redirect()->route('user.index')->with('status_success','User success removed');
    }*/

    public function postRegister(Request $request)
    {
        $rules = [
            'name'=>'required',
            'email'=>'required|email|unique:App\User,email',
            'npassword'=>'required|min:8',
            'cpassword'=>'required|same:npassword'
        ];

        $messages = [
            'name.required'=>'Su nombre es requerido',
            'email.required'=>'Su correo electronico es requerido',
            'email.email'=>'El formato de su correo electronico es invalido',
            'email.unique'=>'Ya existe un usuario registrado con este correo',
            'npassword.required'=>'Por favor escriba una contraseña',
            'npassword.min'=>'La contraseña debe de contener al menos 8 caracteres',
            'cpassword.required'=>'Es necesario confirmar el password',
            'cpassword.min'=>'La confirmación de la contraseña debe de tener al menos 8 caracteres',
            'cpassword.same'=>'Las contraseñas no coinciden'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()) {
            //return back()->withErrors($validator)->with('status_success','Se ha producido un error');
            return response()->json([
                'estado' => 'errorvalidacion',
                'mensaje'=> $validator->errors()->all(),
                'class_name' => 'danger'
            ]);
        }else{
            $user = new User;
            $user->name = e($request->input('name'));
            $user->email = e($request->input('email'));
            $user->password = Hash::make($request->input('npassword'));
            if ($user->save()) {
                //return redirect()->route('user.index')->with('status_success','El usuario se genero con exito');
                return response()->json([
                    'estado' => 1,
                    'mensaje'=>'El usuario se genero con exito',
                    'class_name' => 'success'
                ]);
            }else{
                return response()->json([
                    'estado' => 0,
                    'mensaje'=>'Ocurrio un error. Intentalo de nuevo',
                    'class_name' => 'success'
                ]);
            }
        }

    }

    public function updatepassword(Request $request)
    {
        

        $rules = [

            'password'=>'required|min:8'
        ];
        $messages = [

            'password.required'=>'Por favor escriba una contraseña',
            'password.min'=>'La contraseña debe de contener al menos 8 caracteres'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()) {
            return response()->json([
                'estado' => 'errorvalidacion',
                'mensaje'=> $validator->errors()->all(),
                'class_name' => 'danger'
            ]);
            //return back()->withErrors($validator)->with('status_success','Se ha producido un error');
        }else{

            $id = e($request->input('id_user_now'));
            $user = User::findOrFail($id);
            $user->password = Hash::make($request->input('password'));

            if($user->save()) {
                return response()->json([
                    'estado' => 1,
                    'mensaje'=>'El password se actualizo con exito',
                    'class_name' => 'success'
                ]);
             //return redirect()->route('user.index')->with('status_success','El password se actualizo con exito');
            }
        }
    }

    public function delete_user($id){
        $user = User::find($id);
        $user->estatus=0;
        if ($user->update()) {
            return response()->json([
                "estado"=>1,
                "mensaje"=>"El usuario se dio de baja en el sistema"
            ]);
        }else{
            return response()->json([
                "estado"=>0,
                "mensaje"=>"Ocurrio un error. Intentalo de nuevo"
            ]);
        }
    }

}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')
@section('contenido')
<div class="container"><br>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h5>Crear Rol</h5></div>

                <div class="card-body">
                    @include('custom.message')
                    <form action="{{route('role.store')}}" method="post">
                    @csrf
                    <div class="container">
                        <h4>Datos requeridos</h4>
                        <div class="form-group">
                            
                            <input type="text" class="form-control" name="name" id="name" value="{{old('name')}}" placeholder="Nombre">
                        </div>
                        <div class="form-group">
                            
                            <input type="text" class="form-control"  name="slug" id="slug" value="{{old('slug')}}" placeholder="slug">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="description"  id="description" rows="3" placeholder="Descripción">
                            {{old('description')}}
                            </textarea>    
                        </div>
                        <hr>
                        <h4>Full Access</h4>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="fullaccessyes" name="full-access" class="custom-control-input" value="yes"
                            @if(old('full-access') == "yes")
                                checked
                            @endif
                            >
                            <label class="custom-control-label" for="fullaccessyes">Yes</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="fullaccessno" name="full-access" class="custom-control-input" value="no"
                            @if(old('full-access') == "no")
                                checked
                            @endif
                            @if(old('full-access') === null)
                                checked
                            @endif
                            >
                            <label class="custom-control-label" for="fullaccessno">No</label>
                        </div>
                        <hr>
                        <h4>Lista de permisos</h4>
                        @foreach($permissions as $permission)
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="permission_{{$permission->id}}" value="{{$permission->id}}" name="permission[]"
                            @if(is_array(old('permission')) && in_array("$permission->id", old('permission')))
                                checked
                            @endif
                            >

                            <label class="custom-control-label" for="permission_{{$permission->id}}">{{$permission->id}}-{{$permission->name}}<em> ( {{$permission->description}} )</em></label>
                        </div>
                        @endforeach
                        <br>
                        <input type="submit" class="btn btn-primary" value="Guardar">
                    </div>
                    </form>
                    {{-- {!! dd(old()) !!} --}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')
@section('contenido')
<div class="container"><br>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h2>Editar Usuarios</h2></div>

                <div class="card-body">
                    @include('custom.message')
                    <form action="{{route('user.update',$user->id)}}" method="post">
                    @csrf
                    @method('put')
                    <div class="container">
                        <h4>Requiere datos</h4>
                        <div class="form-group">
                            <input type="text" class="form-control" name="name" id="name" value="{{old('name',$user->name)}}" placeholder="Nombre">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"  name="email" id="email" value="{{old('email',$user->email)}}" placeholder="slug">
                        </div>
                        {{-- <div class="form-group">
                            <input type="password" class="form-control" name="password" id="password" value="old{{'email',$user->password}}" placeholder="Ingresa el password">
                        </div> --}}
                        {{-- {{$user->roles[0]->name}} --}}
                        <div class="form-group">
                            <select name="roles" id="roles" class="form-control">
                            <option value="selecciona">Seleciona un rol</option>
                            @foreach($roles as $role)
                                <option value="{{$role->id}}"
                                    @isset($user->roles[0]->name)
                                        @if($role->name == $user->roles[0]->name)
                                           selected 
                                        @endif
                                    @endisset
                                >{{$role->name}}</option>
                            @endforeach
                            </select>
                        </div>
                        <hr>
                        <input type="submit" class="btn btn-primary" value="Guardar">
                        <a class="btn btn-danger" href="{{route('user.index')}}">Regresar</a>
                    </div>
                    </form>
                    {{-- {!! dd(old()) !!} --}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/view.blade.php
@extends('layouts.admin')

@section('contenido')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h2>Mostra Usuario</h2></div>

                <div class="card-body">
                    @include('custom.message')
                    <form action="{{route('user.show',$user->id)}}" method="post">
                    @csrf
                    @method('put')
                    <div class="container">
                        <h4>Datos</h4>
                        <div class="form-group">
                            <input type="text" class="form-control" name="name" id="name" value="{{old('name',$user->name)}}" placeholder="Nombre" disabled>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"  name="email" id="email" value="{{old('email',$user->email)}}" placeholder="slug" disabled>
                        </div>
                        {{-- <div class="form-group">
                            <input type="text" class="form-control" name="password" id="password" value="{{Crypt::decrypt($user->password)}};" placeholder="Ingresa el password" disabled>
                        </div> --}}
                        {{-- {{$user->roles[0]->name}} --}}
                        <div class="form-group">
                            <select name="roles" id="roles" class="form-control" disabled>
                            <option>Seleciona un rol</option>
                            @foreach($roles as $role)
                                <option value="{{$role->id}}"
                                    @isset($user->roles[0]->name)
                                        @if($role->name == $user->roles[0]->name)
                                           selected 
                                        @endif
                                    @endisset
                                >{{$role->name}}</option>
                            @endforeach
                            </select>
                        </div>
                        <hr>
                        {{-- <input type="submit"  value="Guardar"> --}}
                        {{-- <a class="btn btn-success" href="{{route('role.edit',$role->id)}}">Edit</a> --}}
                        <a class="btn btn-danger" href="{{route('user.index')}}">Regresar</a>
                    </div>
                    </form>
                    {{-- {!! dd(old()) !!} --}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection